# Generated by Django 5.1.1 on 2024-10-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorty',
            new_name='Category',
        ),
    ]
